import React, { Component } from 'react';
import './App.css';
import StickyWidget from './components/StickyWidget'

class App extends Component {
  render() {
    return (
      <div className="App">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis condimentum turpis. Vestibulum sed odio dapibus sem volutpat pharetra. Morbi vehicula neque varius leo fermentum, et auctor mi pulvinar. Etiam efficitur, nisi non aliquam finibus, ex elit molestie velit, id eleifend ligula metus sed ipsum. Ut elementum quam nec luctus tincidunt. Proin sed aliquet justo. In varius mattis metus. Aenean dictum sem velit, at lacinia lacus luctus at. Sed dapibus tincidunt dolor, id venenatis massa suscipit nec. Proin sagittis lorem ac libero luctus cursus. Integer dui risus, elementum quis luctus a, mattis in erat. Nullam rutrum nulla non quam pellentesque porttitor.

          Praesent dapibus risus sit amet turpis posuere, ut eleifend lorem ornare. Sed ex est, fringilla et auctor eu, ultricies eget sem. Cras aliquam magna ut metus venenatis, et commodo eros pharetra. Nullam et ante interdum, viverra lorem in, ultrices nisl. Proin pulvinar urna neque, consectetur aliquet purus vulputate sed. Aenean erat nulla, commodo sed nunc a, vulputate vulputate quam. Sed egestas orci eget sem efficitur aliquam.

          Pellentesque volutpat justo a tristique fringilla. Maecenas malesuada neque at rutrum viverra. Fusce elit dui, consectetur ac dolor non, efficitur iaculis lectus. Vestibulum gravida ligula sit amet ultricies efficitur. Etiam ac mauris blandit, ultricies urna nec, laoreet tellus. Praesent nisl urna, laoreet vel laoreet quis, pellentesque sit amet lorem. Quisque nisi velit, cursus at orci eget, congue fermentum velit. Quisque ut mauris vitae diam scelerisque convallis. Quisque ut ipsum nec magna accumsan auctor id a ante. Cras elementum imperdiet metus id dignissim. Fusce feugiat eget diam et vestibulum. Aliquam nec massa sed quam gravida aliquam. In sit amet metus efficitur, interdum ex sit amet, sagittis turpis. In non venenatis lacus. Praesent scelerisque in orci vel ultrices. Fusce sagittis, turpis a rhoncus tristique, risus nunc dignissim metus, ut facilisis nisl tortor et enim.

          Mauris vel turpis vitae dui pharetra pellentesque. Nam ullamcorper blandit pellentesque. Vivamus sit amet neque mattis, porta orci et, condimentum enim. Donec varius sit amet ligula id dapibus. Quisque in lorem id magna tempus venenatis ac ut ipsum. Pellentesque a lacus eget sem ultricies tristique a sit amet sem. Etiam vitae sodales nunc. Nulla consectetur sem magna, vitae tristique magna pharetra scelerisque. Nam feugiat, velit vel eleifend tristique, libero elit pharetra nulla, id suscipit ligula arcu vel ante. Donec posuere ligula imperdiet nisi pharetra pellentesque. Fusce vel mi quis nisi bibendum malesuada. Nunc ac eros ac velit aliquet vulputate. Sed id elit dolor.

          Etiam tellus nisi, luctus at vehicula nec, ultrices et massa. Proin auctor massa sed ex pellentesque venenatis. Fusce consequat nec leo sed tempus. Duis eu varius nulla. In faucibus a neque quis consequat. In interdum in odio in pellentesque. Mauris aliquam augue nec neque tristique rutrum. Ut malesuada, tortor id sagittis rhoncus, quam nunc scelerisque sem, sit amet commodo elit arcu id magna. Aliquam ornare erat a magna bibendum lacinia. Morbi scelerisque lobortis tellus, id ornare libero fringilla a. Donec ut orci ullamcorper, ornare nibh at, pretium erat. Donec vitae dolor lorem. Sed pharetra elit finibus, iaculis nibh a, tristique magna. Donec finibus erat quis libero ornare, at rhoncus mauris imperdiet. Sed condimentum, sapien at accumsan congue, arcu urna interdum leo, mollis mollis nibh leo at ante. Ut rhoncus ex a est scelerisque viverra.

          Suspendisse condimentum, urna nec rutrum ornare, dui turpis laoreet arcu, scelerisque laoreet ipsum est non sapien. Suspendisse bibendum elit sed leo interdum, quis auctor magna suscipit. Nunc dictum purus vel sodales egestas. Suspendisse potenti. Nunc consectetur, arcu vel faucibus sollicitudin, magna enim accumsan erat, ultrices commodo leo lacus et metus. Suspendisse ac nisi eget justo lobortis viverra eu vitae arcu. Morbi in libero sit amet eros tempor porttitor eget in erat. Sed sodales justo eu orci ullamcorper, id fermentum mauris feugiat. Aliquam aliquet, nisi nec aliquam euismod, nulla erat suscipit eros, id lacinia nisi tortor sed nunc. Pellentesque venenatis metus in aliquam molestie.

          Quisque porta dapibus ligula sit amet feugiat. Mauris egestas a turpis a pellentesque. Proin faucibus et eros et aliquam. Vestibulum in arcu ac sem placerat sagittis sit amet vitae tortor. Cras sit amet nunc velit. Vestibulum nec finibus nisi, eu viverra sapien. Nullam eget fermentum nulla. Duis vel lectus sodales dolor volutpat mattis vel non arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus.

          Pellentesque pharetra euismod metus eu fermentum. Ut scelerisque lacus sit amet dolor porta venenatis. Cras auctor augue est, ac vestibulum lorem euismod sit amet. Vestibulum eget magna nec nunc commodo feugiat. Maecenas tempus ligula a fermentum vehicula. Pellentesque mattis felis nec lorem porttitor, vel iaculis est interdum. Donec ut maximus lectus, ut condimentum tellus. Phasellus nec velit in neque tempus consequat a nec metus. Aliquam vel lectus at dolor sagittis interdum. Donec tempor, est ut fermentum varius, augue eros ultricies magna, non dignissim tortor metus quis mi.

          In scelerisque dignissim fringilla. Nullam nibh ex, efficitur venenatis quam ac, interdum lacinia nulla. Nullam ut nunc quis arcu egestas tempus a iaculis metus. Proin est lorem, feugiat nec tortor at, facilisis semper ex. In cursus mattis ullamcorper. Praesent eu odio eget nisl lacinia dapibus vitae a libero. Nam a porta nisl. Fusce tempus lectus odio, eget eleifend ex tincidunt sed.

          Praesent mollis leo at leo auctor vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam aliquet tortor sit amet convallis pretium. Fusce eget fermentum mauris. Donec auctor condimentum lacus, at interdum felis placerat ac. Nullam convallis lorem non ante ultricies efficitur a rutrum lacus. Sed dignissim venenatis risus sagittis interdum. Pellentesque eu tristique enim. Duis in mattis nibh, quis tristique quam.

          Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam dapibus a sapien vestibulum imperdiet. Pellentesque finibus fringilla tellus. Proin commodo nunc eu sem interdum, in condimentum ligula scelerisque. Quisque nec lectus sit amet magna lacinia semper sit amet eget tortor. Cras orci sem, pulvinar eget volutpat quis, efficitur ac ligula. Pellentesque id feugiat tortor. Phasellus enim dolor, efficitur eget quam viverra, suscipit efficitur orci. Donec eu sapien porttitor, rutrum erat id, consequat eros. Pellentesque pulvinar elit ut quam elementum ultrices.

          Aenean et neque at lacus viverra lacinia. Praesent justo tortor, ornare at elementum sit amet, molestie at justo. Nunc imperdiet diam sed tellus posuere porttitor. Aliquam tincidunt dui est, non euismod odio aliquam id. Praesent cursus, metus ut ullamcorper volutpat, turpis eros venenatis enim, sollicitudin tincidunt magna dolor vel mi. Mauris ut eros neque. Vestibulum ipsum tortor, blandit tempor lacus eget, rutrum fermentum tortor. Phasellus tempor aliquam orci, sed viverra orci suscipit sit amet. Ut facilisis mi turpis. Nunc dictum est a est venenatis sollicitudin. Morbi id cursus nisi. Pellentesque interdum auctor lectus, et vulputate lectus porta et. Maecenas in fermentum urna. Suspendisse potenti. Sed erat urna, malesuada vitae fringilla ut, porttitor sed tortor.

          Curabitur a est non felis ullamcorper tincidunt eu non urna. Donec consequat ligula quis ante tristique, ac ultricies nunc egestas. Aenean eget urna elit. Donec tristique quam sed nibh fermentum sollicitudin. Curabitur vel tortor finibus, fermentum sem a, feugiat ex. Nullam dolor dui, venenatis eu ante dapibus, euismod rutrum lectus. In nisi felis, consequat nec elit eu, consectetur facilisis mi. Etiam lacus lectus, ullamcorper eget sollicitudin a, tincidunt ut purus. Quisque gravida ipsum augue, quis sagittis ligula aliquam sed. Nam dui libero, porta non ornare in, molestie at libero. Integer at blandit urna. Mauris suscipit varius est, sed efficitur justo consequat vitae. Aliquam nec risus ipsum. Proin luctus nulla quam, sollicitudin commodo nibh aliquam varius. Integer molestie euismod risus, nec molestie enim accumsan fringilla.

          Duis condimentum fringilla nulla ut euismod. Vivamus tincidunt egestas eros, at fermentum nisi porta vitae. Nulla vulputate malesuada dignissim. Sed a venenatis dui. Ut molestie finibus justo, sit amet feugiat diam condimentum vitae. Vestibulum ante magna, rutrum elementum molestie a, posuere at diam. Aenean vitae ipsum tristique, accumsan nulla ut, efficitur leo. Sed at ex risus. Pellentesque mattis augue ligula, id dignissim sapien semper sit amet. Nullam a posuere leo, sed pulvinar lectus. Vivamus pellentesque felis diam, non vulputate libero maximus eget. Quisque eget condimentum felis. Cras id vehicula tellus.

          Nulla condimentum fringilla tristique. Donec scelerisque facilisis nisl eget semper. Maecenas hendrerit sem in lectus molestie aliquam. Quisque fringilla risus ac lobortis molestie. Praesent orci enim, cursus vel nunc eget, ultricies lobortis enim. Sed metus sem, ullamcorper a ultricies non, viverra at tortor. Nam sodales ut augue a maximus. Fusce ullamcorper pharetra enim, id luctus enim ultricies eget. Vestibulum vitae vestibulum velit. Aliquam vel velit dui. Donec quam mi, commodo ut lorem non, porttitor eleifend tellus. Nunc vitae mollis purus. Phasellus non convallis mi.
        <StickyWidget />
      </div>
    );
  }
}

export default App;
